[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.devnet]
sol_raiser = "Eu4kchg5AA7yEjAnSH3yTdShVM6jW1wpsSxgAPLDi6Uz"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
